dist: xenial
language: python
sudo: false

python:
  - 3.6
  - 3.7
  - nightly

matrix:
  allow-failure:
    - python: nightly

install:
  - pip install scipy
  - pip install .  # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v  # Test against installed code
