dist: xenial
language: python
sudo: false

python:
  - 3.6
  - 3.7
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - pip install codecov
  - pip install .       # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v --cov-report=xml --cov=intergalactic # Test against installed code

after_success:
  - codecov
