dist: xenial
language: python
sudo: false

python:
  - "3.6"
  - "3.7"

install:
  - pip install .  # Test installation correctness
  - pip install .[dev]  # Test development dependencies

script:
  - pytest -v  # Test against installed code
