# imf = [
#         salpeter     = Salpeter 1955,
#         chabrier     = Chabrier 2003,
#         ferrini      = Ferrini, Palla & Penco 1998,
#         kroupa       = Kroupa 2002,
#         miller_scalo = Miller & Scalo 1979,
#         starburst    = Starburst 1999,
#         maschberger  = Maschberger 2012
#       ]

# sol_ab = [
#            ag89 = Anders & Grevesse 1989,
#            gs98 = Grevesse & Sauval 1998,
#            as05 = Asplund et al. 2005,
#            as09 = Asplund et al. 2009,
#            he10 = Heger 2010
#          ]

# sn_ia_selection = [
#                     1 = SNIa Matteucci
#                     2 = SNIa Tornambe
#                     3 = SNIa Ruiz-Lapuente
#                     4 = SNIa Kobayashi09
#                   ]

z: 0.02
lim_yields: GAV
massive_yields: CLI
sol_ab: ag89
fe_coef: 1
imf: kroupa
imf_alpha: 2.35
imf_m_up: 40
alpha_bin_stars: 0.05
sn_ia_selection: 3
