name: tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - 3.7.15
          - 3.8.15
          - 3.9.15
          - 3.10.8
          - 3.11.0
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest
        pip install codecov
    - name: Install Starmatrix
      run: |
        pip install .
        pip install .[dev]
    - name: Test against installed code
      run: pytest -v --cov-report=xml --cov=starmatrix
    - uses: codecov/codecov-action@v1
